name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile C files
      run: 
        gcc main.c -o main.o
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
          name: Build-artifact
          path: ${{github.workspace}}
