name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile C files
      run: 
        gcc main.c -o main.o
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
          name: Build-artifact
          path: ${{github.workspace}}/main.o

  
  # This workflow contains a single job called "build"
  Deploy:
    # The type of runner that the job will run on
    runs-on: windows-latest
    environment: 
      name: dev
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Deploy Stage 
        run: echo Downloading Build Artificates!
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          Name: Build-artifact
          Path: ${{github.workspace}}/main.o
